covoiturage_homepage:
    path:     /
    defaults: { _controller: CovoiturageBundle:Default:index }
covoiturage_Lister:
    path:     /Lister
    defaults: { _controller: CovoiturageBundle:Covoiturage:Lister }
covoiturage_Listeradmin:
    path:     /Listeradmin
    defaults: { _controller: CovoiturageBundle:Covoiturage:Lister_admin }
covoiturage_Afficher:
    path:     /Afficher
    defaults: { _controller: CovoiturageBundle:Covoiturage:Afficher }
covoiturage_Ajouter:
    path:     /Ajouter
    defaults: { _controller: CovoiturageBundle:Covoiturage:Ajouter }
covoiturage_Modifier:
    path:     /Modifier
    defaults: { _controller: CovoiturageBundle:Covoiturage:Modifier }
covoiturage_Supprimer:
    path:     /Supprimer
    defaults: { _controller: CovoiturageBundle:Covoiturage:Supprimer }
covoiturage_Chercher:
    path:     /Chercher
    defaults: { _controller: CovoiturageBundle:Covoiturage:Chercher }
covoiturage_Signaler:
    path:     /Signaler
    defaults: { _controller: CovoiturageBundle:Covoiturage:Signaler }
SupprimerCov_admin:
    path:     /SupprimerCov
    defaults: { _controller: CovoiturageBundle:Covoiturage:Supprimer_admin }
Getlist:
    path:     /Getlist
    defaults: { _controller: CovoiturageBundle:Covoiturage:getlist }
AjoutMobile:
    path:     /AjoutMobile/{depart}/{destination}/{date}/{type}
    defaults: { _controller: CovoiturageBundle:Covoiturage:AjoutMobile }
getAdrByName:
    path:     /getAdrByName/{nom}
    defaults: { _controller: CovoiturageBundle:Covoiturage:getAdrByName }
